version: "2.1"
services:
  drawio:
    image: jgraph/drawio
    container_name: drawio
    ports:
      - 8080:8080
    restart: unless-stopped

  bookstack:
    image: lscr.io/linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Taipei
      - APP_URL=http://10.1.1.9:6875 #Must Have
      - DB_HOST=bookstack_db
      - DB_PORT=3306
      - DB_USER=bookstack
      - DB_PASS=bookstackpass
      - DB_DATABASE=bookstackapp
    #volumes:
    #  - /path/to/bookstack_app_data:/config
    ports:
      - 6875:80
    restart: unless-stopped
    depends_on:
      - bookstack_db

  bookstack_db:
    image: lscr.io/linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Taipei
      - MYSQL_ROOT_PASSWORD=bookstackpass
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=bookstackpass
    #volumes:
    #  - /path/to/bookstack_db_data:/config
    restart: unless-stopped    
